# Generated by Django 4.2.17 on 2025-01-25 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verificationrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='verificationrequest',
            unique_together={('user', 'status')},
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='professional',
        ),
    ]
