# Generated by Django 5.0 on 2025-01-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='professionals', to='services.category'),
        ),
    ]
