# Generated by Django 4.2.17 on 2025-01-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_verificationrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verificationrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='professional',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='users.professional'),
        ),
        migrations.AlterUniqueTogether(
            name='verificationrequest',
            unique_together={('professional', 'status')},
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='user',
        ),
    ]
