# Generated by Django 4.2.17 on 2025-01-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscriptionplan_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
