# Generated by Django 5.0 on 2025-01-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_address_woreda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalprofile',
            old_name='category',
            new_name='categories',
        ),
    ]
