# Generated by Django 5.1.4 on 2025-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_professional_user_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='preferred_payment_method',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
