# Generated by Django 4.2.17 on 2025-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_verificationrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='end_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], max_length=20),
        ),
    ]
