# Generated by Django 4.2.17 on 2025-01-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscriptionplan_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='subscription',
            new_name='subscription_plan',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, default='chapa', max_length=50, null=True),
        ),
    ]
