# Generated by Django 5.1.4 on 2025-01-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customer_preferred_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.RemoveField(
            model_name='professional',
            name='skills',
        ),
        migrations.AddField(
            model_name='professional',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='professional_skills', to='users.skill'),
        ),
    ]
