# Generated by Django 5.0 on 2025-01-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0004_rename_category_professionalprofile_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='services.category'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='users.skill'),
        ),
    ]
