# Generated by Django 4.2.17 on 2025-01-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_subscription_payment_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='cost',
            field=models.FloatField(editable=False),
        ),
    ]
