# Generated by Django 4.2.17 on 2025-01-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_payment_amount_alter_subscriptionplan_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
