# Generated by Django 5.1.4 on 2025-01-06 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_admin_permission_adminlog_admin_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='business_card',
            field=models.ImageField(blank=True, null=True, upload_to='business_cards'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
