# Generated by Django 4.2.17 on 2025-01-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_portfolio_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalprofile',
            old_name='availability',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
