# Generated by Django 4.2.17 on 2025-01-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_professional_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='professional',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
