# Generated by Django 4.2.17 on 2025-01-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0008_remove_customer_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='common.category'),
        ),
    ]
