# Generated by Django 4.2.17 on 2025-02-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number_of_services_booked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
