# Generated by Django 4.2.17 on 2025-01-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_professional_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
