# Generated by Django 4.2.17 on 2025-02-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_current',
        ),
    ]
