# Generated by Django 4.2.17 on 2025-02-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_address_user_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
