# Generated by Django 4.2.17 on 2025-02-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_professional_requests_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='requests_left',
            new_name='num_of_request',
        ),
    ]
