# Generated by Django 4.2.17 on 2025-02-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_requests_left_professional_num_of_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='balance',
        ),
    ]
