# Generated by Django 4.2.17 on 2025-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_is_blocked_user_is_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('individual', 'Individual'), ('admin', 'Admin')], default='individual', max_length=30),
        ),
    ]
