# Generated by Django 4.2.17 on 2025-04-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0027_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgprofessional',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='orgprofessional',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='orgprofessional',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.RemoveField(
            model_name='admin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='admin',
            name='full_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='number_of_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='tx_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='number_of_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professional',
            name='tx_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.professional'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.professional'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='users.professional'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='common.category'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='users.skill'),
        ),
        migrations.DeleteModel(
            name='OrgCustomer',
        ),
        migrations.DeleteModel(
            name='OrgProfessional',
        ),
    ]
