# Generated by Django 4.2.17 on 2025-04-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_rename_account_type_user_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='users.professional'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='professional',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan', to='users.professional'),
        ),
    ]
