# Generated by Django 4.2.17 on 2025-04-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_servicepost_customer_and_more'),
        ('users', '0033_customer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='service',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicebooking'),
        ),
    ]
