# Generated by Django 4.2.17 on 2025-04-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_payment_service_payment_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_code', models.PositiveIntegerField(choices=[(442, 'Awash Bank'), (445, 'Commercial Bank of Ethiopia'), (448, 'Dashen Bank'), (451, 'Zemen Bank'), (454, 'Bank of Abyssinia'), (457, 'NIB International Bank'), (460, 'Oromia International Bank'), (463, 'United Bank'), (466, 'Wegagen Bank')])),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='users.professional')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
    ]
