# Generated by Django 4.2.17 on 2025-04-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_withdrawaltransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawaltransaction',
            old_name='txt_ref',
            new_name='tx_ref',
        ),
    ]
