# Generated by Django 4.2.17 on 2025-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_rename_full_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_code',
            field=models.PositiveIntegerField(choices=[(130, 'Abay Bank'), (772, 'Addis International Bank'), (207, 'Ahadu Bank'), (656, 'Awash Bank'), (347, 'Bank of Abyssinia'), (571, 'Berhan Bank'), (128, 'CBEBirr'), (946, 'Commercial Bank of Ethiopia (CBE)'), (893, 'Coopay-Ebirr'), (880, 'Dashen Bank'), (1, 'Enat Bank'), (301, 'Global Bank Ethiopia'), (534, 'Hibret Bank'), (612, 'Hijra Bank'), (202, 'Lion Bank'), (325, 'Nib International Bank'), (896, 'Oromia Bank'), (287, 'Siinqee Bank'), (465, 'Tsehay Bank'), (614, 'ZamZam Bank'), (451, 'Zemen Bank')]),
        ),
    ]
