# Generated by Django 4.2.17 on 2025-05-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='professional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='users.professional'),
        ),
    ]
