# Generated by Django 4.2.17 on 2025-05-05 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_verificationrequest_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='users.admin'),
        ),
    ]
