# Generated by Django 4.2.17 on 2025-05-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_verificationrequest_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professional',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
