# Generated by Django 4.2.17 on 2025-05-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_customer_report_count_professional_report_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='professional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan', to='users.professional'),
        ),
    ]
