# Generated by Django 4.2.17 on 2025-05-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_servicepostreport_options_and_more'),
        ('users', '0049_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('job_post', 'Job Post'), ('direct_request', 'Direct Request')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicerequest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicebooking'),
        ),
    ]
