# Generated by Django 4.2.17 on 2025-05-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_payment_payment_type_payment_service_request_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
