# Generated by Django 4.2.17 on 2025-02-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('verification_request', 'Verification Request'), ('system', 'System'), ('service_post', 'Service Post'), ('service_request', 'Service Request'), ('payment', 'Payment'), ('application', 'Application'), ('status_update', 'Status Update'), ('message', 'Message')], default='info', max_length=20),
        ),
    ]
