# Generated by Django 4.2.17 on 2025-02-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'info'), ('new_job', 'New Job Post'), ('job_apply', 'Job Application'), ('verify_request', 'Verification Request'), ('verify_response', 'Verification Response'), ('new_booking', 'New Booking'), ('new_job_request', 'New Job Request'), ('new_job_response', 'Job Request Response'), ('new_complain', 'New Complaint'), ('new_feedback', 'New Feedback'), ('new_review', 'New Review')], default='info', max_length=20),
        ),
    ]
