# Generated by Django 4.2.17 on 2025-02-03 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_payment_amount_alter_professional_balance_and_more'),
        ('services', '0002_servicepost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_post', to='users.address'),
        ),
    ]
