# Generated by Django 4.2.17 on 2025-01-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0008_remove_customer_profile_image_and_more'),
        ('services', '0004_rename_service_servicepost_servicepostapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='common.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
