# Generated by Django 4.2.17 on 2025-02-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_review_complain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
    ]
