# Generated by Django 4.2.17 on 2025-02-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicepost_urgency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='agreed_price',
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('booked', 'booked'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
