# Generated by Django 4.2.17 on 2025-02-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_complain_booking_alter_complain_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
