# Generated by Django 4.2.17 on 2025-04-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0014_alter_servicepost_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_booking', to='services.servicepostapplication'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_posts', to='common.category'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicepostapplication',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicepostapplication',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_applications', to='services.servicepost'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_recieved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
