# Generated by Django 4.2.17 on 2025-04-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_customer_description'),
        ('services', '0015_alter_servicebooking_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_posts', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='servicepostapplication',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_applications', to='users.professional'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_recieved', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='users.professional'),
        ),
    ]
