# Generated by Django 4.2.17 on 2025-05-05 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0016_alter_servicepost_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePostReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='services.servicepost')),
            ],
        ),
    ]
