# Generated by Django 4.2.17 on 2025-05-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_servicepostreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepostreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Post Report', 'verbose_name_plural': 'Service Post Reports'},
        ),
        migrations.RenameField(
            model_name='servicepostreport',
            old_name='reported_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='servicepostreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
