# Generated by Django 4.2.17 on 2025-05-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_servicepostreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancled', 'canceled'), ('accepted', 'Accepted'), ('completed', 'completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
